//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleAssistance.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerRequest()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int RequestId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> MechanicId { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual MechanicsDetail MechanicsDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
